version: "3"

networks:
  gitea:
    external: false

services:
  server:
    image: gitea/gitea:1.16.5
    container_name: gitea
    environment:
      - USER_UID=978
      - USER_GID=974
    restart: always
    networks:
      - gitea
    volumes:
      - ./gitea:/data
#      - /home/git/.ssh/:/data/git/.ssh
      - /etc/timezone:/etc/timezone:ro
      - /etc/localtime:/etc/localtime:ro
    ports:
      - "127.0.0.1:3030:3000"
      - "127.0.0.1:2222:22"