version: "3.8"

services:
  nextcloud:
    image: nextcloud/all-in-one:latest
    restart: unless-stopped
    container_name: nextcloud-aio-mastercontainer
    ports:
      - "8081:8080"
    environment:
      - APACHE_IP_BINDING=127.0.0.1
      - APACHE_PORT=11000
      - NEXTCLOUD_DATADIR=/mnt/nas 
      - NEXTCLOUD_MOUNT=/mnt/
      - SKIP_DOMAIN_VALIDATION=true
    volumes:
      - /run/docker.sock:/var/run/docker.sock
      - nextcloud_aio_mastercontainer2:/mnt/docker-aio-config

volumes:
  nextcloud_aio_mastercontainer2:
    name: nextcloud_aio_mastercontainer2